service: dropboxapp

custom:
  bucket: specialtopicsbucket
  table: minidropbox

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"

functions:
  uploadFile:
    handler: uploadFile.uploadFile
    events:
      - s3: 
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*

  deleteFile:
    handler: deleteFile.deleteFile
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectRemoved:*


resources:
  Resources:
    MinidropboxTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.table}
